site_name: Guia de Alternativas de Carregamento Tesla (2025)

theme:
  name: material
  language: pt
  palette: 
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: deep orange

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue grey
      accent: deep purple

  features:
  - navigation.top
  - navigation.tabs
  - navigation.footer
  - navigation.indexes
  - navigation.path
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - search.highlight
  - search.share
  - toc.integrate
  - content.tabs.link

copyright: Copyright &copy; 2025 AMME

extra:
  social:
    - icon: simple/github
      link: https://github.com/AmmeProjects/guia-verao
    - icon: material/web
      link: https://amme.com.pt
    - icon: simple/facebook
      link: https://www.facebook.com/ammeportugal
    - icon: material/email
      link: mailto:geral@amme.com.pt
  analytics:
    provider: google
    property: G-9G85XVVS3V
    feedback:
      title: Esta página ajudou?
      ratings:
        - icon: material/heart
          name: Esta página ajudou
          data: 1
          note: >-
            Obrigado pelo feedback!
        - icon: material/heart-broken
          name: Poderia ser melhor
          data: 0
          note: >- 
            Obrigado pelo feedback! Ajude-nos a melhorar
            enviando um email para <a href="mailto:geral@amme.com.pt">geral@amme.com.pt</a>.

extra_css:
  - stylesheets/extra.css

markdown_extensions: 
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes

plugins:
  - open-in-new-tab

nav:
  - Introdução: index.md
  - Requisitos: requisitos.md
  - Quando Usar: quando.md
  - Riscos: riscos.md
  - Preço: preco.md
  - Recomendações: recomendacoes.md
  - Localizações:
      - Fátima: locations/fatima.md
      - Alcácer do Sal: locations/alcacer.md
      - Loulé: locations/loule.md
      - Alcantarilha: locations/alcantarilha.md
      - Mealhada: locations/mealhada.md






  